---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  WA_DB_USERNAME: "root"
  WA_DB_CONNECTION_IDLE_TIMEOUT: {{ .Values.db.idleTimeout | quote }}
{{- if eq .Values.db.engine  "MYSQL" }}
  WA_DB_PORT: {{ .Values.db.mysql.port | quote }}
{{- else }}
  WA_DB_PORT: {{ .Values.db.pgsql.port | quote }}
{{- end }}
{{- if .Values.db.enabled  }}
  WA_DB_HOSTNAME: {{ template "fullname" . }}-db
{{- else }}
  WA_DB_HOSTNAME: {{ .Values.db.host | quote }}
{{- end }}
  WA_CONFIG_ON_DB: "1"
  WA_TCP_LISTEN_ADDRESS: "any"
  WA_DB_ENGINE: "{{ .Values.db.engine }}"
