{{- if .Values.web.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.web.ingress.annotations }}
  annotations:
{{ toYaml .Values.web.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host:  {{ .Values.web.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 443
{{- end -}}
