{{- if .Values.multiconnect }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: {{ template "fullname" . }}-master
spec:
  clusterIP: None
  ports:
  - port: 6250
    targetPort: 6250
    protocol: TCP
    name: messaging
  - port: 6251
    targetPort: 6251
    protocol: TCP
    name: contacts
  - port: 6252
    targetPort: 6252
    protocol: TCP
    name: control
  - port: 6253
    targetPort: 6253
    protocol: TCP
    name: healthcheck
  selector:
    name: {{ template "fullname" . }}-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: {{ template "fullname" . }}-master
spec:
  replicas: {{ .Values.master.replicas }}
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      name: {{ template "fullname" . }}-master
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-master
        release: {{ template "fullname" . }}
{{- if .Values.core.podAnnotations }}
      annotations:
{{ toYaml .Values.core.podAnnotations | indent 8 }}
{{- end }}
    spec:
      restartPolicy: {{ .Values.master.restartPolicy }}
      containers:
      - name: whatsapp-master
        image: "{{ .Values.master.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.core.resources | indent 12 }}
        command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
        ports:
        - containerPort: 6250
          protocol: TCP
          name: messaging
        - containerPort: 6251
          protocol: TCP
          name: contacts
        - containerPort: 6252
          protocol: TCP
          name: control
        - containerPort: 6253
          protocol: TCP
          name: healthcheck
        env:
        - name: WA_APP_MULTICONNECT
          value: '1'
        - name: COREAPP_EXTERNAL_PORTS
          value: '6250,6251,6252,6253'
        - name: WA_MASTER_NODE
          value: '1'
        - name: WA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_USERNAME
        - name: WA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_PASSWORD
        - name: COREAPP_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}
        volumeMounts:
        - name: whatsapp-media
          mountPath: /usr/local/wamedia
      volumes:
      - name: whatsapp-media
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- end }}
