{{- if eq .Values.db.engine "MYSQL" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-mysql-pvc
  labels:
    release: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.volumeSize }}
{{- if .Values.db.efs }}
  storageClassName: efs
{{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-db
  labels:
    release: {{ template "fullname" . }}
spec:
  selector:
    app: {{ template "fullname" . }}-mysql
  ports:
  - protocol: TCP
    port: {{ .Values.db.port }}
    targetPort: 3306
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-mysql
  labels:
    release: {{ template "fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-mysql
        release: {{ template "fullname" . }}
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.db.mysql.repository }}:{{ .Values.db.mysql.tag }}"
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_PASSWORD
        - name: MYSQL_DATABASE
          value: {{ .Values.db.hostname }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-mysql-pvc
{{- end }}