{{- if eq .Values.db.engine "PGSQL" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-pgsql-pvc
  labels:
    release: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.volumeSize }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-db
  labels:
    release: {{ template "fullname" . }}
spec:
  selector:
    app: {{ template "fullname" . }}-postgres
  ports:
  - protocol: TCP
    port: {{ .Values.db.port }}
    targetPort: 5432
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-postgres
  labels:
    release: {{ template "fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-postgres
        release: {{ template "fullname" . }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.db.pgsql.repository }}:{{ .Values.db.pgsql.tag }}"
        env:
        - name: POSTGRES_DB
          value: {{ .Values.db.hostname }}
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_PASSWORD
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: pgsql-persistent-storage
      volumes:
      - name: pgsql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-pgsql-pvc
{{- end }}