{{- if .Values.preUpgrade.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-upgrade-db
  labels:
    app.kubernetes.io/name: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-upgrade-db
      labels:
        #app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ template "fullname" . }}
    spec:
      # This shows how to use a simple value. This will look for a passed-in value
      # called restartPolicy. If it is not found, it will use the default value.
      # {{ default "Never" .restartPolicy }} is a slightly optimized version of the
      # more conventional syntax: {{ .restartPolicy | default "Never" }}
      restartPolicy: {{ .restartPolicy | default "OnFailure" }}
      containers:
      - name: upgrade-db-job
        image: "{{ .Values.core.repository }}:{{ .Values.image.tag }}"
        env:
        - name: WA_DB_UPGRADE
          value: "1"
        - name: WA_DB_ENGINE
          value: {{ .Values.db.engine }}
        - name: WA_TCP_LISTEN_ADDRESS
          value: 'any'
        - name: WA_APP_MULTICONNECT
          value: '1'
        - name: WA_CONFIG_ON_DB
          value: '1'
        - name: COREAPP_EXTERNAL_PORTS
          value: '6250,6251,6252,6253'
        - name: WA_DB_HOSTNAME
          value: {{ template "fullname" . }}-db
        - name: WA_DB_PORT
          value: {{ .Values.db.port | quote }}
        - name: WA_DB_CONNECTION_IDLE_TIMEOUT
          value: {{ .Values.db.idleTimeout | quote }}
        - name: WA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_USERNAME
        - name: WA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_PASSWORD
        command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
{{- end -}}
