---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
data:
  WA_DB_USERNAME: {{ .Values.db.user | b64enc }}
  WA_DB_PASSWORD: {{ .Values.db.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tokenSecretName }}
data:
  WA_API_KEY: {{ template "livenessProbeToken" . }}
