{{- if eq .Values.wamedia.type "nfs" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}
spec:
  capacity:
    storage: {{ .Values.wamedia.volumeSize }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.wamedia.nfs.server }}
    path: "{{ .Values.wamedia.nfs.path }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.wamedia.volumeSize }}

{{- else if eq .Values.wamedia.type "efs" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wamedia.volumeSize }}
  storageClassName: efs
{{- else if eq .Values.wamedia.type "ceph" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wamedia.volumeSize }}
  storageClassName: {{ .Values.wamedia.ceph.storageClassName }}
{{ else }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}
  labels:
    release: {{ template "fullname" . }}
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.wamedia.volumeSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/local/wamedia"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}
  labels:
    release: {{ template "fullname" . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wamedia.volumeSize }}
{{- end }}