{{- if .Values.multiconnect }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}-web-autoscaler
  labels:
    release: {{ template "fullname" . }}
spec:
  maxReplicas: {{ .Values.web.maxReplicas }}
  minReplicas: {{ .Values.web.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ template "fullname" . }}-web
  targetCPUUtilizationPercentage: 60
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    release: {{ template "fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: web
  selector:
    name: {{ template "fullname" . }}-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    release: {{ template "fullname" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: {{ template "fullname" . }}-web
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-web
        release: {{ template "fullname" . }}
{{- if .Values.web.podAnnotations }}
      annotations:
{{ toYaml .Values.web.podAnnotations | indent 8 }}
{{- end }}
    spec:
      restartPolicy: {{ .Values.web.restartPolicy }}
      containers:
      - name: whatsapp-web
        image: "{{ .Values.web.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.web.resources | indent 12 }}
        ports:
        - containerPort: 443
          protocol: TCP
          name: web
        command: ["/opt/whatsapp/bin/wait_on_mysql.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
        env:
        - name: WA_DB_ENGINE
          value: {{ .Values.db.engine }}
        - name: WA_APP_MULTICONNECT
          value: '1'
        - name: WA_DB_HOSTNAME
        {{- if .Values.db.enabled  }}
          value: {{ template "fullname" . }}-db
        {{ else }}
          value: {{ .Values.db.host | quote }}
        {{- end }}
        - name: WA_DB_PORT
          value: {{ .Values.db.port | quote }}
        - name: WA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_USERNAME
        - name: WA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "secretName" . }}
              key: WA_DB_PASSWORD
        - name: WA_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tokenSecretName }}
              key: WA_API_KEY
        - name: WA_WEB_SERVERNAME
          value: {{ template "fullname" . }}-web
        volumeMounts:
        - name: whatsapp-media
          mountPath: /usr/local/wamedia
        livenessProbe:
          exec:
            command:
            - 'bash'
            - '-c'
            - 'curl --fail -k https://localhost:443/v1/health --header "Authorization: Apikey ${WA_API_KEY}"'
          initialDelaySeconds: 30
          periodSeconds: 15
      volumes:
      - name: whatsapp-media
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
{{- end }}
